### PR TITLE
example: Deprecate the webusb package dependency

### PR DESCRIPTION
**Pull request by windowsair**
The webusb feature is already included in the usb package. Let's deprecate the extra webusb package.

### CODE REVIEW

**Comment by thegecko** [comment]
Sorry for the delay replying here. By adding a dependency on `node-usb` in the examples it stops it from working in a browser environment.
We need to ensure dapjs can be used in the web (it's original intent) as well as on the desktop with `node-usb` poly-filling `webusb`

Please comment if I've missed a point!

**Comment by windowsair** [comment]
In the folder for each example there is a `web.html`, they should not depend on any other js file except dapjs, I'm not sure if this is what you want?

**Comment by thegecko** [comment]
I'm keen web users don't assume they need to download node-usb to use the examples.

Perhaps a better approach would be to reorganise the examples into web ones and desktop ones?

**Comment by windowsair** [comment]
I think it's better to update the documentation. Some of the content in the current documentation is no longer applicable.

**Review by thegecko — APPROVED** [review]

**Pull request merged**
