### PR TITLE
Apply stricter type checks and remove Node.js dependency from DAPLink

### PR DESCRIPTION
**Pull request by philipphenkel**
- Apply stricter TS rules: strictNullChecks and noImplictReturns
- TypeScript 3.0 compliance
- Remove NodeJS.Timer from DAPLink

A first step towards #35

### CODE REVIEW

**Comment by arekzaluski** [comment]
Hi @philipphenkel. I'm sorry for keeping this PR open for such a long time. Can you rebase it on master? I'll check and test it on Monday.

**Comment by philipphenkel** [comment]
@arekzaluski No worries, I'm very happy if don't have to maintain a fork. I will rebase the PR.

**Comment by philipphenkel** [comment]
@arekzaluski  Rebase done. Please note that I had no chance to run tests.

**Comment by thegecko** [comment]
I believe all concerns have been addresses in other PRs, can this be closed now?

**Comment by philipphenkel** [comment]
@thegecko Yes, I think so. Good job!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request closed without merging**
